version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    container_name: test-elasticsearch
    environment:
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=false
      # - network.host=0.0.0.0
      # - http.port=9200
      # - transport.tcp.port=9300
    ports:
      - "9209:9200"
      - "9309:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elastic
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge